// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/time;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # Remove a todo from the shared list
    #
    # + return - returns can be any of following types
    # http:NoContent (Todo deleted)
    # http:NotFound (Todo not found)
    # http:Unauthorized (Not signed in)
    resource function delete todos/[string todoId](http:RequestContext ctx)
            returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized();
        }
        boolean|error removed = deleteTodoRow(todoId);
        if removed is error {
            return removed;
        }
        if !removed {
            return notFoundError("todo not found");
        }
        return http:NO_CONTENT;
    }

    # Every todo on the shared list
    #
    # + return - returns can be any of following types
    # http:Ok (Page of todos)
    # http:Unauthorized (Not signed in)
    resource function get todos(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns TodoPage|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized();
        }
        int pageLimit = 'limit > 100 ? 100 : 'limit;
        [TodoRow[], int] resolved = check listTodoRows(pageLimit, offset);
        TodoRow[] rows = resolved[0];
        int total = resolved[1];
        Todo[] todos = from TodoRow row in rows select toTodo(row);
        string? next = ();
        if offset + pageLimit < total {
            next = string `/todos?limit=${pageLimit}&offset=${offset + pageLimit}`;
        }
        string? previous = ();
        if offset > 0 {
            int prevOffset = offset - pageLimit;
            if prevOffset < 0 {
                prevOffset = 0;
            }
            previous = string `/todos?limit=${pageLimit}&offset=${prevOffset}`;
        }
        TodoPage result = {count: total, next, previous, data: todos};
        return result;
    }

    # Mark a todo done or not done
    #
    # + return - returns can be any of following types
    # http:Ok (Updated todo)
    # http:NotFound (Todo not found)
    # http:Unauthorized (Not signed in)
    resource function patch todos/[string todoId](http:RequestContext ctx, @http:Payload TodoUpdate payload)
            returns Todo|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized();
        }
        TodoRow|error? updated = updateTodoDone(todoId, payload.done);
        if updated is error {
            return updated;
        }
        if updated is () {
            return notFoundError("todo not found");
        }
        return toTodo(updated);
    }

    # Add a new todo to the shared list
    #
    # + return - returns can be any of following types
    # http:Created (Todo created)
    # http:BadRequest (Invalid todo text)
    # http:Unauthorized (Not signed in)
    resource function post todos(http:RequestContext ctx, @http:Payload TodoCreate payload)
            returns http:Created|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized();
        }
        string text = payload.text.trim();
        if text == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "todo text must not be empty"}};
        }
        string createdBy = caller.username.trim() != "" ? caller.username : caller.userId;
        TodoRow created = check insertTodo(text, createdBy);
        return <http:Created>{body: toTodo(created)};
    }
}

# Projects a stored row into the wire shape the contract declares.
#
# + row - the persisted todo
# + return - the API-facing record, with `createdAt` as an RFC3339 string
function toTodo(TodoRow row) returns Todo => {
    id: row.id,
    text: row.text,
    done: row.done,
    createdBy: row.createdBy,
    createdAt: time:utcToString(row.createdAt)
};

function toUnauthorized() returns ErrorUnauthorized => {
    body: {code: 401, message: "not signed in"}
};

function notFoundError(string message) returns ErrorNotFound => {
    body: {code: 404, message}
};

public type Todo record {|
    string id;
    string text;
    boolean done;
    # username of the user who added it
    string createdBy;
    string createdAt;
|};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoPage record {|
    # total matching items
    int count;
    # relative URI of the next page
    string? next = ();
    # relative URI of the previous page
    string? previous = ();
    Todo[] data;
|};

public type Error record {|
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
|};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoCreate record {|
    string text;
|};

public type TodoUpdate record {|
    boolean done;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
